### ISSUE TITLE
Bit Or / Logical Or

### ISSUE THREAD

**Issue by nopnop2002** [adafruit/TinyWireM#5]
This is Bit Or
`#if defined(__AVR_AT90Mega169__) | defined(__AVR_ATmega169__) | \
    defined(__AVR_AT90Mega165__) | defined(__AVR_ATmega165__) | \
    defined(__AVR_ATmega325__) | defined(__AVR_ATmega3250__) | \
    defined(__AVR_ATmega645__) | defined(__AVR_ATmega6450__) | \
    defined(__AVR_ATmega329__) | defined(__AVR_ATmega3290__) | \
    defined(__AVR_ATmega649__) | defined(__AVR_ATmega6490__)`

This is Logical Or
`#if defined(__AVR_AT90Mega169__) || defined(__AVR_ATmega169__) || \
    defined(__AVR_AT90Mega165__) || defined(__AVR_ATmega165__) || \
    defined(__AVR_ATmega325__) || defined(__AVR_ATmega3250__) || \
    defined(__AVR_ATmega645__) || defined(__AVR_ATmega6450__) || \
    defined(__AVR_ATmega329__) || defined(__AVR_ATmega3290__) || \
    defined(__AVR_ATmega649__) || defined(__AVR_ATmega6490__)`

Which is right?

**Comment by PaintYourDragon** [comment]
Since it's all dealing with booleans, either will work. Logical OR might be more 'right' in some pedantic conceptual sense (if this were in the C code rather than preprocessor directives, there'd be some performance benefit to the logical OR, evaluated left-to-right and ending on the first true statement), but functionally the same thing's coming out the other end regardless.
